export const firebaseLooper = snapshot => {
    let data= [];
    snapshot.forEach(doc => {
        data.push({
            ...doc.data(),
            id: doc.id //custom id generated by Firebase to be mapped as a property
        })
    })
    return data;
}